package br.com.itau.letscode.ialmeida.DynamoDB.model;

import br.com.itau.letscode.ialmeida.DynamoDB.model.enums.Priority;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "tasks")
@Data
public class Task {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    private String title;
    private String detail;

    @DynamoDBTypeConvertedEnum
    private Priority priority;

    @DynamoDBTypeConvertedTimestamp
    private Date createDate;

    @DynamoDBTypeConvertedTimestamp
    private Date expectDate;

    @DynamoDBTypeConvertedTimestamp
    private Date endDate;

}
